import type { Metadata } from "next";
import { Playfair, Outfit, Cairo } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import "./globals.css";
import clsx from "clsx";
import LayoutConfig from '../components/LayoutConfig';
import Alert from '../components/Alert';

const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PROJECT_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={clsx(
          playfair.variable,
          outfit.variable,
          cairo.variable,
          "antialiased scroll-smooth w-svw touch-none"
        )}
      >
        <NextIntlClientProvider>
          <div className="relative overflow-x-hidden w-full">{children}</div>
          <LayoutConfig />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
