import type { Metadata } from "next";
import { Poppins, Playfair } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

import "./globals.css";
import clsx from "clsx";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JoysMaker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body
        className={clsx(poppins.variable, playfair.variable, "antialiased scroll-smooth w-svw")}
      >
        <NextIntlClientProvider>
          <div className="relative overflow-x-hidden w-full">
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
