import { login, signup } from "./actions";

export const metadata: Metadata = {
  title: "JoysMaker | Login",
  description: "Generated by create next app",
};

export default async function LoginPage({searchParams}) {

  const {redirectTo} = await searchParams
  


  
  return (
    <form className="mt-3 bg-surface shadow rounded p-3 w-2/3 flex flex-col justify-center items-center gap-3">
      <input type="text" name='redirect' value={redirectTo} className='hidden' />
      <label className="w-full " htmlFor="email">
        Email:
      </label>
      <input
        className="w-full rounded outline-none border border-text-secondary p-1 px-3 "
        id="email"
        name="email"
        type="email"
        required
      />
      <label className="w-full " htmlFor="password">
        Password:
      </label>
      <input
        className="w-full rounded outline-none border border-text-secondary p-1 px-3 "
        id="password"
        name="password"
        type="password"
        required
      />
      <button
        className="w-full bg-primary p-2 text-xl text-surface font-semibold rounded cursor-pointer hover:bg-primary-hover"
        formAction={login}
      >
        Log in
      </button>
      <button
        className="w-full bg-primary p-2 text-xl text-surface font-semibold rounded cursor-pointer hover:bg-primary-hover"
        formAction={signup}
      >
        Sign up
      </button>
    </form>
  );
}
