
import { login, signup, signInWithGoogle } from "./actions";
import { FaGoogle } from "react-icons/fa";

export const metadata: Metadata = {
  title: "WhoHands | Login",
  description: "Generated by create next app",
};

export default async function LoginPage({ searchParams }) {
  const { redirectTo } = await searchParams;

  return (
    <main className="w-full px-10 flex justify-start items-center py-5 pt-20 flex-col ">
      <form className="mt-3 bg-surface shadow rounded p-3 w-2/3 flex flex-col justify-center items-center gap-3">
        <input
          type="text"
          name="redirect"
          defaultValue={redirectTo}
          className="hidden"
        />
        <label className="w-full " htmlFor="email">
          Email:
        </label>
        <input
          className="w-full rounded outline-none border border-text-secondary p-1 px-3 "
          id="email"
          name="email"
          type="email"
          required
        />
        <label className="w-full " htmlFor="password">
          Password:
        </label>
        <input
          className="w-full rounded outline-none border border-text-secondary p-1 px-3 "
          id="password"
          name="password"
          type="password"
          required
        />
        <button
          className="w-full bg-primary p-2 text-xl text-surface font-semibold rounded cursor-pointer hover:bg-primary-hover"
          formAction={login}
        >
          Log in
        </button>
        <button
          className="w-full bg-primary p-2 text-xl text-surface font-semibold rounded cursor-pointer hover:bg-primary-hover"
          formAction={signup}
        >
          Sign up
        </button>
      </form>
      <form>
        <button
          formAction={signInWithGoogle}
          className="min-w-72 min-h-10 m-3 bg-primary hover:bg-primary-hover duration-300 cursor-pointer px-5 py-2 rounded shadow flex justify-center items-center gap-3 "
        >
          <FaGoogle className="text-white text-lg" />
          <p className="text-white font-poppins font-medium capitalize">
            continue with google
          </p>
        </button>
      </form>
    </main>
  );
}
